# Generated by Django 6.0.5 on 2026-05-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('tel_emergencia', models.CharField(max_length=15, verbose_name='Línea de Emergencia ')),
                ('has_palliative_unit', models.BooleanField(default=False)),
                ('available_schedules', models.TextField(help_text='Horarios de atención general y especialidades')),
            ],
        ),
    ]
