# Generated by Django 6.0.5 on 2026-05-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='available_schedules',
            new_name='calendario_atencion',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='has_palliative_unit',
            new_name='tiene_unidad_paliativa',
        ),
    ]
