# Generated by Django 6.0.5 on 2026-05-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita_fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=15)),
                ('tipo', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('TELEMEDICINA', 'Telemedicina')], default='PRESENCIAL', max_length=15)),
                ('enlace_virtual', models.URLField(blank=True, help_text='Enlace a la videollamada', max_length=500, null=True)),
                ('razon_cancelado', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
