# Generated by Django 6.0.5 on 2026-05-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duracion_minutos',
            field=models.IntegerField(default=30, help_text='Duración estimada de la cita en minutos'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='es_recurrente',
            field=models.BooleanField(default=False, help_text='Indica si la cita se repite periódicamente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fecha_fin_recurrencia',
            field=models.DateField(blank=True, help_text='Fecha límite hasta la cual se repite la cita', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='frecuencia_recurrencia',
            field=models.CharField(blank=True, choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], help_text='Frecuencia de repetición de la cita', max_length=15, null=True),
        ),
    ]
