# Generated by Django 6.0.5 on 2026-05-29 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('medicamentos_json', models.JSONField(blank=True, default=list)),
                ('requiere_control_especial', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('DISPENSADA', 'Dispensada'), ('EXPIRADA', 'Expirada')], default='EMITIDA', max_length=20)),
                ('firma_digital_5B', models.CharField(max_length=256)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receta_medica', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_doctor', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
