# Generated by Django 6.0.5 on 2026-05-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetamedica',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='recetas_pdfs/', verbose_name='Documento PDF de la Receta'),
        ),
    ]
