# Generated by Django 6.0.5 on 2026-05-29 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_recetamedica_archivo_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroESAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('dolor', models.IntegerField(default=0, help_text='Intensidad del dolor (0-10)')),
                ('cansancio', models.IntegerField(default=0, help_text='Nivel de cansancio (0-10)')),
                ('nausea', models.IntegerField(default=0, help_text='Nivel de náusea (0-10)')),
                ('depresion', models.IntegerField(default=0, help_text='Nivel de depresión (0-10)')),
                ('ansiedad', models.IntegerField(default=0, help_text='Nivel de ansiedad (0-10)')),
                ('somnolencia', models.IntegerField(default=0, help_text='Nivel de somnolencia (0-10)')),
                ('apetito', models.IntegerField(default=0, help_text='Falta de apetito (0-10)')),
                ('respiracion', models.IntegerField(default=0, help_text='Dificultad para respirar (0-10)')),
                ('nota_adicional', models.TextField(blank=True, help_text='Observaciones adicionales del paciente', null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_esas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro ESAS',
                'verbose_name_plural': 'Registros ESAS',
                'ordering': ['-fecha'],
                'unique_together': {('paciente', 'fecha')},
            },
        ),
    ]
