# Generated by Django 6.0.5 on 2026-05-29 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=13, unique=True, verbose_name='licencia')),
                ('especialidad', models.CharField(max_length=13, unique=True, verbose_name='especialidad')),
                ('dpi', models.CharField(max_length=13, unique=True, verbose_name='documento personal')),
                ('birth_date', models.DateField()),
                ('emergency_name', models.CharField(max_length=20, unique=True, verbose_name='nombre de emergencia')),
                ('emergency_contact', models.CharField(max_length=8, verbose_name='contacto de emergencia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
